### ISSUE TITLE
큰 사진 파일은 갤러리에 인식되는데 시간이 좀 걸림

### ISSUE THREAD

**Issue by kdrkdrkdr** [kdrkdrkdr/PIT4ADB#1]
그래서 인식 안 됐을 경우에는 1초 쉬고 다시 시도하는 그런 코드가 필요함

**Comment by LeePC** [comment]
그럴때에는 이미지 크기를 줄여보는걸 추천드림 그러면 잘되더라구 ㅋㅋ

**Comment by kdrkdrkdr** [comment]
> 그럴때에는 이미지 크기를 줄여보는걸 추천드림 그러면 잘되더라구 ㅋㅋ

1. 이미지 크기 줄이기
2. 이미지 인식될 때까지 루프 돌리기

일단 이렇게 할 것 같고 당분간 이거는 개발 안 할거라.. 
메인 프로젝트 하고 나서 고쳐보겠다 ㄱㅅㄱㅅ

**Comment by LeePC** [comment]
그리고 저의 마지막 질문이 있습니다.....
txt파일을 파파고로 번역하는 툴같은거 만들어볼 생각 있으신지요??
파이썬으로 해보려고 해도 안되서 질문드립니다

**Comment by kdrkdrkdr** [comment]
> 그리고 저의 마지막 질문이 있습니다..... txt파일을 파파고로 번역하는 툴같은거 만들어볼 생각 있으신지요?? 파이썬으로 해보려고 해도 안되서 질문드립니다 쯔꾸르 게임 번역하는게 필요하다보니 ㅠㅠ

시간 나면 만들게요.. 제가 지금 파파고에 이름 사전 적용하려고 하는 중이라..

**Comment by LeePC** [comment]
저기 일정비용내고 커미션 개발같은것도 해주실수있나요??

https://user-images.githubusercontent.com/8704225/154791634-7ce13458-311d-411b-abfb-cb2ed6fa8102.mp4

대충 이런건데
저게 1줄코드로 만들어진거라고 하더라구요 개발자 말로는
A2M 툴 1줄코드로 만든거라고 하는데
1줄코드를 짜면 알아서 그 코드를 읽고 자동화 시켜준다는데
커미션 받아주실수 있나요??

**Comment by kdrkdrkdr** [comment]
해당 시스템이 어떻게 돌아가는지도 모르고, 말씀하신 A2M툴이 뭔지도 잘 모릅니다..
그리고 아마 1줄 코드라는게 진짜 한 줄 코드가 아니라 프로그램 내부에 있는 코드에 의해 돌아갈거에요. 
아마 해당 프로그램 만드신 개발자분께 가서 여쭤보시는게 좋을 것 같네요.

**Comment by LeePC** [comment]
개발자가 중국인이라 QQ외에는 연결할방법이 없으니 말씀드립니다 ㅠㅠ
QQ계정도 없고 만들수도 없어서요....
그리고 저는 포물선도 그릴줄 모르고 삼각함수도 모릅니다 그냥 커미션을 할수없나해서 질문드린거 뿐이구요 ㅠㅠ

**Comment by LeePC** [comment]
/summon falling_block 64 19.457 0 {Block:"redstone_block",Time:100b,Data:2,Motion:[%((%p-64)/127*5.55),0.0,0.0]} 
이게 제가 전에 쓰던 코드입니다

**Comment by kdrkdrkdr** [comment]
아니 근데 이거 저도 잘 몰라요. 말씀하셔서 처음 안거에요. 
다른분께 여쭤보세요.
이외에 연락하시려면 디코 kdr#9450 로 부탁드립니다.
이 레포지토리는 파파고 자동 이미지 번역 레포니까요..

**Comment by kdrkdrkdr** [comment]
+ 지금은 바쁜 시기라 외주/커미션 받지 않습니다. K고3 이라서요

**Comment by LeePC** [comment]
마지막으로 응응#3546 으로 친추들어갔을껍니다
